"""Add last_uploaded_at to user_group_association

Revision ID: 04b4a3baadaf
Revises: 2c30829882bf
Create Date: 2025-03-20 02:22:59.949316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b4a3baadaf'
down_revision: Union[str, None] = '2c30829882bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group_association', sa.Column('last_uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group_association', 'last_uploaded_at')
    # ### end Alembic commands ###
